'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';

interface Escalation {
  ticket_id: string;
  user_id: string;
  caller_name: string;
  reason: string;
  urgency: 'low' | 'medium' | 'high';
  summary: string;
  preferred_contact: string;
  status: string;
  created_at: string;
}

export default function EscalationsDashboard() {
  const [escalations, setEscalations] = useState<Escalation[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchEscalations = async () => {
    try {
      const res = await fetch('/api/escalations');
      const data = await res.json();
      setEscalations(data.escalations || []);
    } catch (err) {
      console.error('Failed to load escalations', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEscalations();
    const interval = setInterval(fetchEscalations, 5000); // Auto-refresh every 5s
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-6 md:p-12">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-6">
          <div>
            <div className="flex items-center gap-2 text-indigo-400 font-mono text-sm mb-1">
              <span>🎓</span> AI LEARNING COMPANION DASHBOARD
            </div>
            <h1 className="text-3xl font-bold tracking-tight">Teacher Assistance & Escalation Requests</h1>
            <p className="text-slate-400 text-sm mt-1">
              Human-in-the-loop support requests generated by the voice AI agent (Day 7).
            </p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={fetchEscalations}
              className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-sm font-medium transition border border-slate-700"
            >
              🔄 Refresh List
            </button>
            <Link
              href="/"
              className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-sm font-medium text-white transition shadow-lg shadow-indigo-500/20"
            >
              ← Back to Voice Agent
            </Link>
          </div>
        </div>

        {/* Stats bar */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
            <div className="text-xs text-slate-400 font-medium">TOTAL REQUESTS</div>
            <div className="text-2xl font-bold mt-1 text-white">{escalations.length}</div>
          </div>
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
            <div className="text-xs text-slate-400 font-medium">OPEN TICKETS</div>
            <div className="text-2xl font-bold mt-1 text-amber-400">
              {escalations.filter((e) => e.status === 'Open').length}
            </div>
          </div>
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
            <div className="text-xs text-slate-400 font-medium">HIGH URGENCY</div>
            <div className="text-2xl font-bold mt-1 text-rose-400">
              {escalations.filter((e) => e.urgency === 'high').length}
            </div>
          </div>
        </div>

        {/* Tickets List */}
        {loading ? (
          <div className="text-center py-12 text-slate-400">Loading escalation tickets...</div>
        ) : escalations.length === 0 ? (
          <div className="bg-slate-900/50 border border-slate-800/80 rounded-2xl p-12 text-center">
            <div className="text-4xl mb-3">✅</div>
            <h3 className="text-lg font-semibold text-slate-200">No Open Escalations</h3>
            <p className="text-slate-400 text-sm max-w-md mx-auto mt-1">
              When a student asks for a teacher or expresses high frustration, the agent will ask permission and create a ticket here.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4">
            {escalations.map((item) => (
              <div
                key={item.ticket_id}
                className="bg-slate-900 border border-slate-800 hover:border-slate-700 rounded-xl p-5 transition space-y-3"
              >
                <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800/60 pb-3">
                  <div className="flex items-center gap-3">
                    <span className="font-mono text-sm font-bold text-indigo-400 bg-indigo-950/60 border border-indigo-800/60 px-2.5 py-1 rounded-md">
                      {item.ticket_id}
                    </span>
                    <span className="font-semibold text-slate-200">{item.caller_name}</span>
                    <span className="text-xs text-slate-500 font-mono">({item.user_id})</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span
                      className={`text-xs px-2.5 py-1 rounded-full font-semibold border ${
                        item.urgency === 'high'
                          ? 'bg-rose-950/60 text-rose-300 border-rose-800/60'
                          : item.urgency === 'medium'
                          ? 'bg-amber-950/60 text-amber-300 border-amber-800/60'
                          : 'bg-emerald-950/60 text-emerald-300 border-emerald-800/60'
                      }`}
                    >
                      {item.urgency.toUpperCase()} URGENCY
                    </span>
                    <span className="text-xs px-2.5 py-1 rounded-full font-medium bg-slate-800 text-slate-300 border border-slate-700">
                      {item.status}
                    </span>
                  </div>
                </div>

                <div>
                  <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">Reason for Escalation</div>
                  <p className="text-sm font-medium text-slate-200">{item.reason}</p>
                </div>

                {item.summary && (
                  <div className="bg-slate-950/60 border border-slate-800/80 rounded-lg p-3 text-xs text-slate-300 font-sans">
                    <span className="font-semibold text-slate-400 block mb-0.5">Session Summary:</span>
                    {item.summary}
                  </div>
                )}

                <div className="flex items-center justify-between text-xs text-slate-500 pt-1">
                  <div>
                    Preferred Contact: <span className="text-slate-400 font-medium">{item.preferred_contact}</span>
                  </div>
                  <div>
                    Created: <span className="font-mono text-slate-400">{new Date(item.created_at).toLocaleString()}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
